# [[plugins]]
# repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger="<tab>"
  let g:UltiSnipsJumpForwardTrigger="<c-b>"
  let g:UltiSnipsJumpBackwardTrigger="<c-z>"
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_gui_enable=1
'''

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  highlight GitGutterAdd    ctermfg=2
  highlight GitGutterChange ctermfg=1
  highlight GitGutterDelete ctermfg=3
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  " 保存時のみ実行
  let g:ale_lint_on_text_changed = 0
  " sign symbols
  let g:ale_sign_error = '✘'
  let g:ale_sign_warning = '⚠'
  " message format
  let g:ale_echo_msg_format = '[%linter%]%code: %s [%severity%]'
  highlight link ALEErrorSign Tag
  highlight link ALEWarningSign StorageClass
'''
