[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger="<tab>"
  let g:UltiSnipsJumpForwardTrigger="<c-b>"
  let g:UltiSnipsJumpBackwardTrigger="<c-z>"
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
  let g:nerdtree_tabs_autoclose=0
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
  let g:WebDevIconsNerdTreeAfterGlyphPadding = " "
  if exists('g:loaded_webdevicons')
    call webdevicons#refresh()
  endif
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_gui_enable=1
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
  set background=dark
  let g:ligthline = { 'colorscheme': 'gruvbox' }
'''

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  highlight GitGutterAdd    ctermfg=2
  highlight GitGutterChange ctermfg=1
  highlight GitGutterDelete ctermfg=3
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  " 保存時のみ実行
  let g:ale_lint_on_text_changed = 0
  " sign symbols
  let g:ale_sign_error = '✘'
  let g:ale_sign_warning = '⚠'
  " message format
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  highlight link ALEErrorSign Tag
  highlight link ALEWarningSign StorageClass
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ asyncomplete#force_refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform']
hook_add = '''
  let g:terraform_align=1
  let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'akinsho/bufferline.nvim'

[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
  let g:clang_format#detect_style_file = 1
'''

[[plugins]]
repo = 'mattn/vim-sqlfmt'
hook_add = '''
  let g:sqlfmt_program = "sqlformat --reindent --keyword upper -o %s -"
'''

