[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'suan/vim-instant-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger="<tab>"
'''

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  let NERDTreeShowHidden=1
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_gui_enable=1
'''

[[plugins]]
repo = 'skanehira/translate.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  highlight GitGutterAdd    ctermfg=2
  highlight GitGutterChange ctermfg=1
  highlight GitGutterDelete ctermfg=3
'''

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'yarn install'
on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']
hook_add = '''
  function! EnableJavascript()
    " Setup used libraries
    let g:used_javascript_libs = 'react,vue'
    let b:javascript_lib_use_react = 1
    let b:javascript_lib_use_vue = 1
  endfunction
  autocmd FileType javascript,javascript.jsx call EnableJavascript()
'''

